routes/web.php
<?php

use App\Http\Controllers\ProductController;
use App\Http\Controllers\BasketController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['prefix' => 'products'], function () {
    Route::get('/searchIndex', [ProductController::class, 'searchIndex'])->name('products.search.index');
    Route::get('/search', [ProductController::class, 'search'])->name('products.search');
});

Route::resource('products', ProductController::class);

Route::group(['prefix' => 'basket'], function () {
    Route::get('/', [BasketController::class, 'getAll'])->name('basket.index');
    Route::post('/add/{id}/{price}', [BasketController::class, 'add'])->name('basket.add');
    Route::delete('/delete/{id}', [BasketController::class, 'delete'])->name('basket.delete');
    Route::post('/addQuantity', [BasketController::class, 'addQuantity'])->name('basket.addQuantity');
});

app/Models/Product.php
<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Product extends Model
{
    use HasFactory;
    use SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $guarded = [];

    //Relation
    public function basket()
    {
        return $this->hasOne(Basket::class);
    }

    // Accessors
    public function getCreatedAtAttribute($value)
    {
        return Carbon::parse($value)->format('M d Y, H:i');
    }

    public function getPriceWithSignAttribute($value)
    {
        return $this->attributes['PriceWithSign'] = $this->price." $";
    }

    public function getColorAttribute($value)
    {
        $value = strtolower($value);
        return ucwords($value);
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Models\Product;
use App\Services\Interfaces\ProductServiceInterface;
use App\Services\Interfaces\BasketServiceInterface;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\Redirect;

class ProductController extends Controller
{
    public $successStatusCode = 200;
    private $ProductService;
    private $BasketService;

    public function __construct(ProductServiceInterface $ProductService, BasketServiceInterface $BasketService)
    {
        $this->ProductService = $ProductService;
        $this->BasketService  = $BasketService;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $products = $this->ProductService->getAll();

        return view('product.index', ['result' => $products]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('product.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $valid = array(
            'name'         => 'required|max:250',
            'product_code' => 'required|max:250|unique:products,product_code',
            'quantity'     => 'required|numeric|min:1',
            'price'        => 'required|numeric|between:0,99999999',
            'color'        => 'required|in:BLACK,BLUE,RED,GREEN,YELLOW,WHITE',
            'image'        => 'required|image|mimes:jpeg,png,jpg|max:'.config('app.ProductImageSize'),
        );

        $validator = Validator::make($request->all(), $valid);

        if ($validator->fails()) {
            return Redirect::back()->withInput()->withErrors($validator);
        }

        // Insert new product to database
        $product = $this->ProductService->store($request);

        if ($product instanceof Product) {
            $message = 'Product successfully created.';
        } else {
            $message = 'Product creation encountered a problem!';
        }

        return redirect()->route('products.index')->with(['result' => $message]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function edit(Product $product)
    {
        return view('product.edit')->with(['product' => $product]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Product $product)
    {
        $valid = array(
            'name'         => 'required|max:250',
            'product_code' => 'required|max:250|unique:products,product_code,'.$product->id,
            'quantity'     => 'required|numeric|min:1',
            'price'        => 'required|numeric|between:0,99999999',
            'color'        => 'required|in:BLACK,BLUE,RED,GREEN,YELLOW,WHITE',
            'image'        => 'sometimes|image|mimes:jpeg,png,jpg|max:'.config('app.ProductImageSize'),
        );

        $validator = Validator::make($request->all(), $valid);

        if ($validator->fails()) {
            return Redirect::back()->withInput()->withErrors($validator);
        }

        // update product to database
        $product = $this->ProductService->update($request, $product);

        // update TotalPrice of basket
        $this->BasketService->UpdateTotalPrice($product);

        if ($product instanceof Product) {
            $message = 'Product successfully updated.';
        } else {
            $message = 'Product update encountered a problem!';
        }

        return redirect()->route('products.index')->with(['result' => $message]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function destroy(Product $product)
    {
        $message = $this->ProductService->delete($product);

        return $message;
    }

     /**
     * Show the product search page
     *
     * @return \Illuminate\Http\Response
     */
    public function searchIndex()
    {
        $basket = $this->BasketService->getAll();

        return view('search.index',['result' => $basket]);
    }

    /**
     * Search by product name or sku or code
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function search(Request $request)
    {
        $results = $this->ProductService->search($request);

        return response()->json($results, $this->successStatusCode,);
    }
}

resources/views/product/create.blade.php
@extends('layout')
@section('title', 'Create')
@section('style')
    <style>
        .form-group{margin-bottom: 15px;}
    </style>
@endsection

@section('content')   
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Create Product</div>

                <div class="card-body">
                    <form method="POST" action="{{route('products.store')}}" enctype='multipart/form-data'>
                        @csrf
                        <div class="form-group row">
                            <label for="name" class="col-md-3 col-form-label text-md-right">Names</label>
                            <div class="col-md-9">
                                <input type="text" class="form-control" id="name" value="{{ old('name') }}" name="name" required>
                                @if($errors->has('name'))
                                    <div class="error">{{ $errors->first('name') }}</div>
                                @endif
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="color" class="col-md-3 col-form-label text-md-right">Color</label>
                            <div class="col-md-9">
                                <select class="custom-select" name="color" id="color" aria-label="" required>
                                    <option value="RED" {{ old('color') == 'RED' ? 'selected' : '' }}>Red</option>
                                    <option value="GREEN" {{ old('color') == 'GREEN' ? 'selected' : '' }}>Green</option>
                                    <option value="BLACK" {{ old('color') == 'BLACK' ? 'selected' : '' }}>Black</option>
                                    <option value="BLUE" {{ old('color') == 'BLUE' ? 'selected' : '' }}>Blue</option>
                                    <option value="YELLOW" {{ old('color') == 'YELLOW' ? 'selected' : '' }}>Yellow</option>
                                    <option value="WHITE" {{ old('color') == 'WHITE' ? 'selected' : '' }}>White</option>
                                </select>
                                @if($errors->has('color'))
                                    <div class="error">{{ $errors->first('color') }}</div>
                                @endif
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="product_code" class="col-md-3 col-form-label text-md-right">Product code</label>
                            <div class="col-md-9">
                                <input type="text" class="form-control" id="product_code" value="{{ old('product_code') }}" name="product_code" required>
                                @if($errors->has('product_code'))
                                    <div class="error">{{ $errors->first('product_code') }}</div>
                                @endif
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="quantity" class="col-md-3 col-form-label text-md-right">Quantity</label>
                            <div class="col-md-9">
                                <input type="number" class="form-control" id="quantity" value="{{ old('quantity') }}" name="quantity" min="1" required>
                                @if($errors->has('quantity'))
                                    <div class="error">{{ $errors->first('quantity') }}</div>
                                @endif
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="price" class="col-md-3 col-form-label text-md-right">Price</label>
                            <div class="col-md-9">
                                <div class="input-group mb-3">
                                    <input type="text" class="form-control" id="price" value="{{ old('price') }}" name="price" aria-describedby="basic-addon2" required>
                                    <div class="input-group-append">
                                        <span class="input-group-text" id="basic-addon2">$</span>
                                    </div>
                                </div>
                                @if($errors->has('price'))
                                    <div class="error">{{ $errors->first('price') }}</div>
                                @endif
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="image" class="col-md-3 col-form-label text-md-right">Image</label>
                            <div class="col-md-9">
                                <input type="file" class="form-control" id="image" value="{{ old('image') }}" name="image" required>
                                @if($errors->has('image'))
                                    <div class="error">{{ $errors->first('image') }}</div>
                                @endif
                            </div>
                        </div>
                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-3">
                                <button type="submit" class="btn btn-primary mb-3">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/product/edit.blade.php
@extends('layout')
@section('title', 'Edit')
@section('style')
    <style>
        .form-group{margin-bottom: 15px;}
    </style>
@endsection

@section('content')   
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Edit Product</div>

                <div class="card-body">
                    <form method="POST" action="{{route('products.update', $product->id)}}" enctype='multipart/form-data'>
                        @csrf
                        {{ method_field('PATCH') }}
                        <div class="form-group row">
                            <label for="name" class="col-md-3 col-form-label text-md-right">Names</label>
                            <div class="col-md-9">
                                <input type="text" class="form-control" id="name" value="{{ old('name') ?: $product->name }}" name="name" required>
                                @if($errors->has('name'))
                                    <div class="error">{{ $errors->first('name') }}</div>
                                @endif
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="color" class="col-md-3 col-form-label text-md-right">Color</label>
                            <div class="col-md-9">
                                <select class="custom-select" name="color" id="color" aria-label="" required>
                                    <option 
                                        @if(old('color'))
                                        {{ ( old('color') == 'RED' ) ? 'selected' : '' }}
                                        @else
                                        {{ ( $product->color == 'Red' ) ? 'selected' : '' }}
                                        @endif
                                    value="RED" >Red</option>

                                    <option
                                        @if(old('color'))
                                        {{ ( old('color') == 'GREEN' ) ? 'selected' : '' }}
                                        @else
                                        {{ ( $product->color == 'Green' ) ? 'selected' : '' }}
                                        @endif
                                    value="GREEN">Green</option>

                                    <option 
                                        @if(old('color'))
                                        {{ ( old('color') == 'BLACK' ) ? 'selected' : '' }}
                                        @else
                                        {{ ( $product->color == 'Black' ) ? 'selected' : '' }}
                                        @endif                                   
                                    value="BLACK">Black</option>

                                    <option
                                        @if(old('color'))
                                        {{ ( old('color') == 'BLUE' ) ? 'selected' : '' }}
                                        @else
                                        {{ ( $product->color == 'Blue' ) ? 'selected' : '' }}
                                        @endif                                     
                                    value="BLUE" >Blue</option>

                                    <option
                                        @if(old('color'))
                                        {{ ( old('color') == 'YELLOW' ) ? 'selected' : '' }}
                                        @else
                                        {{ ( $product->color == 'Yellow' ) ? 'selected' : '' }}
                                        @endif                                      
                                    value="YELLOW">Yellow</option>

                                    <option 
                                        @if(old('color'))
                                        {{ ( old('color') == 'WHITE' ) ? 'selected' : '' }}
                                        @else
                                        {{ ( $product->color == 'White' ) ? 'selected' : '' }}
                                        @endif                                     
                                    value="WHITE">White</option>
                                </select>
                                @if($errors->has('color'))
                                    <div class="error">{{ $errors->first('color') }}</div>
                                @endif
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="product_code" class="col-md-3 col-form-label text-md-right">Product code</label>
                            <div class="col-md-9">
                                <input type="text" class="form-control" id="product_code" value="{{ old('product_code') ?: $product->product_code }}" name="product_code" required>
                                @if($errors->has('product_code'))
                                    <div class="error">{{ $errors->first('product_code') }}</div>
                                @endif
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="quantity" class="col-md-3 col-form-label text-md-right">Quantity</label>
                            <div class="col-md-9">
                                <input type="number" class="form-control" id="quantity" value="{{ old('quantity') ?: $product->quantity }}" name="quantity" min="1" required>
                                @if($errors->has('quantity'))
                                    <div class="error">{{ $errors->first('quantity') }}</div>
                                @endif
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="price" class="col-md-3 col-form-label text-md-right">Price</label>
                            <div class="col-md-9">
                                <div class="input-group mb-3">
                                    <input type="text" class="form-control" id="price" value="{{ old('price') ?: $product->price }}" name="price"  aria-describedby="basic-addon2" required>
                                    <div class="input-group-append">
                                        <span class="input-group-text" id="basic-addon2">$</span>
                                    </div>
                                </div>
                                @if($errors->has('price'))
                                    <div class="error">{{ $errors->first('price') }}</div>
                                @endif
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="image" class="col-md-3 col-form-label text-md-right">Image</label>
                            <div class="col-md-9">
                                <input type="file" class="form-control" id="image" value="{{ old('image') ?: $product->image }}" name="image">
                                @if($errors->has('image'))
                                    <div class="error">{{ $errors->first('image') }}</div>
                                @endif
                            </div>
                        </div>
                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-3">
                                <button type="submit" class="btn btn-primary mb-3">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/product/index.blade.php
@extends('layout')
@section('title', 'Home')
@section('style')
    <style>
        #createButton{
            margin-bottom: 20px;
        }
        ul{
            margin:0;padding:0;
        }
        ul>li{
            list-style: none;
            display:inline-block;
        }
        td,th{
            text-align: center;
            vertical-align: middle!important;
        }
        .imageHolder{
            text-align: center;
            justify-content: center; 
            display: flex; 
            flex-direction: row;
            overflow: hidden;
        }
        .imageHolder img{
            object-fit: cover; 
            flex: 1;
            height: 100px;
        }
        a.btn-info{
            color:white;
        }
        a.btn-danger:hover{
            color:black;
        }
    </style>
@endsection

@section('content')   
    @if(session()->get('result'))
        <div class="alert alert-info" role="alert">
            {{ session()->get('result') }}
        </div>
        <hr>
    @endif
    @if( request()->get('message') )
        <div class="alert alert-info" role="alert">
            {{ request()->get('message') }}
        </div>
        <hr>
    @endif

    <a href="{{route('products.create')}}" title="create product" class="btn btn-primary" id="createButton">Create Product</a>
    
    <table class="table table-hover table-sm">
        <thead>
            <tr>
                <th scope="col"></th>
                <th scope="col">Name</th>
                <th scope="col">SKU</th>
                <th scope="col">Code</th>
                <th scope="col">Color</th>
                <th scope="col">Quantity</th>
                <th scope="col">Price</th>
                <th scope="col">Image</th>
                <th scope="col">Created at</th>
                <th scope="col">Actions</th>
            </tr>
        </thead>
        <tbody>
            @php

                if( request()->get('page') ){
                    $i = ((request()->get('page') - 1) * 5) + 1;
                }else{
                    $i = 1; 
                }
            
            @endphp

            @foreach ($result as $product)
                <tr>
                    <td>{{$i}}</td>
                    <td>{{$product->name}}</td>
                    <td>{{$product->sku}}</td>
                    <td>{{$product->product_code}}</td>
                    <td>{{$product->color}}</td>
                    <td>{{$product->quantity}}</td>
                    <td>{{$product->PriceWithSign}}</td>
                    <td><div class="imageHolder"><img alt="product image" src="{{ asset('uploads/productImages/'.$product->image) }}"></div></td>
                    <td>{{$product->created_at}}</td>
                    <td>
                        <ul>
                            <li><a href="{{route('products.edit', $product)}}" title="update product" class="btn btn-info">Update</a></li>
                            <li><button class="btn btn-danger deleteModal" data-attr="{{$product}}" data-toggle="modal" data-target="#deleteModal">Delete</button></li>
                        </ul>
                    </td>
                    @php $i++; @endphp
                </tr>
            @endforeach
        </tbody>
    </table>
    {{ $result->links() }}

    <!-- Delete Modal -->
    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deleteModalLabel">Are you sure?</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                    It will delete your product...
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button id="modalDeleteButton" type="button" class="btn btn-danger">Delete</button>
            </div>
            </div>
        </div>
    </div>
@endsection

@section('script')
    <script type="text/javascript">
        $(document).ready(function(){
            
            $(".deleteModal").click(function () {
                var product = $(this).attr('data-attr');
                $('#modalDeleteButton').attr('data-attr', product);
            });

            $('#modalDeleteButton').click(function () {
                var product= $(this).attr('data-attr');
                let productId = JSON.parse(product).id
                var request = $.ajax({
                    url:`/products/${productId}`,
                    type:"DELETE",
                    headers: {
                        'X-CSRF-TOKEN': '{{csrf_token()}}'
                    },
                    data: {
                        "product": product
                    },
                }).done(function(response){
                    window.location.replace(`/products?message=${response}`);
                }).catch(e=> console.log(e))
            });

        });
    </script>
@endsection